title: Avengers Campaign
description: Information for players of Ashraf's Avengers Campaign
remote_theme: just-the-docs/just-the-docs@v0.10.1

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-toc

search_enabled: true
color_scheme: dark

mermaid:
  version: "10.9.1"
  
